image: ubuntu:latest
before_script:
  - apt-get update -qq
  - apt-get install -qq git
  # Setup SSH deploy keys
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

deploy_staging:
  stage: deploy
  environment:
    name: staging
    url: baleomol.info
  script:
    - ssh centos@108.137.185.185  "whoami && cd /usr/local/lsws/AFFILIODEV/html && sudo git checkout develop && sudo git pull origin develop && sudo composer install && sudo php artisan optimize:clear && sudo php artisan cache:forget spatie.permission.cache && sudo php artisan cache && exit"
  only:
    - develop
